<?php
	$this -> headTitle($title);
?>
<h1><?php echo isset($pluralTitle) ? $pluralTitle: $title; ?></h1>
<?php if(isset($subTitle)) { ?>
    <h6>Parent: <b><?php echo $subTitle; ?></b></h6>
<?php } ?>
<p>
    <a class="btn btn-primary btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'add', 'container' => $container, 'parent' => (string)$parent )); ?>">Add new <?php echo $title; ?></a>
</p>

<?php
if(isset($msg)) {
    echo <<<HTML
        <div class="alert alert-{$msg['type']} alert-dismissable msg">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {$msg['msg']}
        </div>
HTML;
}

if($rows -> getTotalItemCount()> 0) :
?>  
<table class="table">
    <tr>
        <th>Title</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($rows as $row): 
        $browseLink = $this -> url($mainRouteName, array('action' => 'index', 'container' => $container, 'parent' => $row -> id));
    ?>
    <tr>
        <td>
            <?php 
                echo "<a href='$browseLink'>".$this -> escapeHtml($row -> title)."</a>"; 
            ?>
        </td>
        <td>
            <a class="btn btn-default btn-sm" href="<?php echo $browseLink; ?>">List Submenu</a>
            <a class="btn btn-default btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'add', 'container' => $container, 'parent' => $row -> id)); ?>">Add Submenu</a>
            <a class="btn btn-default btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'edit', 'container' => $container, 'parent' => (string)$parent, 'id' => $row -> id)); ?>">Edit</a>
            <a class="btn btn-default btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'delete', 'container' => $container, 'parent' => (string)$parent, 'id' => $row -> id)); ?>">Delete</a>            
            <?php if($row -> active == '0') { ?>
                <a class="btn btn-default btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'enable', 'container' => $container, 'parent' => (string)$parent, 'id' => $row -> id)); ?>">Enable</a>
            <?php } else {?>
                <a class="btn btn-default btn-sm" href="<?php echo $this -> url($mainRouteName, array('action' => 'disable', 'container' => $container, 'parent' => (string)$parent, 'id' => $row -> id)); ?>">Disable</a>
            <?php } ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php
echo $this->paginationControl(
    $rows,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Zf2Navigation'),
    // the route to link to when a user clicks a control link
    array(
        'route' => $mainRouteName,
        'params' => array(
            'parent' => $parent,
            'container' => $container
        )
    )
);
endif;